url: https://experimentsinplay.com
baseurl: ''

# Site settings
title: Experiments in Play
email: experimentsinplay@gmail.com
description: "Experiments in Play is a brand new showcase of inventive and exciting playful experiences that sit at the intersection of games, interactive design, and creative technology."

# Build settings
markdown: kramdown
permalink: pretty
